### ISSUE TITLE
new "Analyse d'URL" button is not intuitive

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#41] opened 2015-09-30 15:47 UTC
It is at the top right of the windows:
![image](https://cloud.githubusercontent.com/assets/328244/10198140/05fe84e2-679b-11e5-99be-9606573d1e5e.png)

Whereas the "Analyses d'URLs" part is at the bottom left:
![image](https://cloud.githubusercontent.com/assets/328244/10198179/31169520-679b-11e5-907e-7f6093b1def1.png)

Maybe a better place for this + button is near the "Analyses d'URLs" section ?

**Comment by nojhamster** [comment] 2015-09-30 15:48
Duplicate of #38

**Closed as completed by nojhamster** 2015-09-30 15:48 UTC
Labels: duplicate
