### ISSUE TITLE
The sort options should be remembered

### ISSUE THREAD

**Issue by tporquet** [ezpaarse-project/analogist#93] opened 2017-05-29 08:45 UTC
The use case is : 
From the general list one selects a search criterion: 

![capture du 2017-05-29 10-42-04](https://cloud.githubusercontent.com/assets/2981650/26542768/7932d8de-445b-11e7-9ce0-a3d79708ddc5.png)

then one goes on a platform listed for this criterion.

![capture du 2017-05-29 10-42-59](https://cloud.githubusercontent.com/assets/2981650/26542804/98805e96-445b-11e7-9451-32484579d230.png)

the "back" button showed above should yield the same filtered list (step one) instead of the complete unfiltered list

**Comment by nojhamster** [comment] 2017-05-29 09:09
Duplicate of #80

**Closed as completed by nojhamster** 2017-05-29 09:09 UTC
Labels: type: enhancement, UI, priority: high
